# JOB LEVEL TEMPLATE:
# Used to build JavaScript
# Reusable
# Meant to be run from the single JavaScriptTemplate pipeline (default), or
#   from a multi-pipeline such as publishing (should specify alternate params)

parameters:
- name: ApiSpecSource
  displayName: ApiSpecSource
  type: string
  default: -apiSpecGitUrl https://raw.githubusercontent.com/PlayFab/API_Specs/master/
- name: CommitMessage
  displayName: CommitMessage
  type: string
  default: Automated build from ADO Pipeline
- name: GitDestBranch
  displayName: GitDestBranch
  type: string
  default: doNotCommit
- name: GitJSetupBranch
  displayName: GitJSetupBranch
  type: string
  default: master
- name: GitSdkGenBranch
  displayName: GitSdkGenBranch
  type: string
  default: master
- name: isVersioned
  displayName: isVersioned
  type: boolean
  default: false
- name: TestServer
  displayName: TestServer
  default: false
- name: SelfTemplateResource
  displayName: SelfTemplateResource
  type: string
  default: self

jobs:
- job: JavaJobTemplate
  steps:
  - bash: echo JavaJobTemplate
- job: JavaTemplate
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: JavaStepTemplate.yml
    parameters:
      ApiSpecSource: ${{ parameters.ApiSpecSource }}
      CommitMessage: ${{ parameters.CommitMessage }}
      GitDestBranch: ${{ parameters.GitDestBranch }}
      GitJSetupBranch: ${{ parameters.GitJSetupBranch }}
      GitSdkGenBranch: ${{ parameters.GitSdkGenBranch }}
      isVersioned: ${{ parameters.isVersioned }}
      TestServer: ${{ parameters.TestServer }}
      SelfTemplateResource: ${{ parameters.SelfTemplateResource }}
