name: Run Maven build

on:
  push:
    branches:
      - 'add-maven-build-github-action'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.7
      
      - run: |
          cd app
          mvn -B package --file pom.xml
      
      - run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging